# Generated by Django 3.2 on 2022-01-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='last_namee',
            new_name='last_name',
        ),
    ]
