# Generated by Django 3.2 on 2022-01-19 01:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editoriales', '0001_initial'),
        ('authors', '0002_rename_last_namee_author_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_pub', models.DateTimeField(default=datetime.datetime(2022, 1, 19, 1, 29, 3, 36075, tzinfo=utc))),
                ('authors', models.ManyToManyField(to='authors.Author')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editoriales.editorial')),
            ],
        ),
    ]
